image: spirogov/gitlab

stages:
  - build
  - api-tests
  - ui-tests
  - report

cache:
  paths:
    - ~/.gradle

build:
  stage: build
  only:
    - master
  script:
    - ./gradlew clean assemble

api-tests:
  stage: api-tests
  only:
    - master
  script:
    - ./gradlew clean api-tests:test api-tests:allureReport
  artifacts:
    name: "allure report"
    paths:
      - api-tests/build/reports/allure-report